language: ruby
rvm:
    - 2.4.1
env:
    - DB=mysql
before_script:
    - cp config/database.test.yml config/database.yml
    - cp .env.example .env
    - bundle install
script:
  # To resolve: Mysql2::Error: Specified key was too long; max key length is 767 bytes
  - echo '[mysqld]' | sudo sh -c 'cat >>  /etc/mysql/my.cnf'
  - echo 'innodb_file_format=Barracuda' | sudo sh -c 'cat >>  /etc/mysql/my.cnf'
  - echo 'innodb_file_per_table=1' | sudo sh -c 'cat >>  /etc/mysql/my.cnf'
  - echo 'innodb_large_prefix=1' | sudo sh -c 'cat >>  /etc/mysql/my.cnf'
  - sudo service mysql restart

  - RAILS_ENV=test bin/rake db:create --trace
  - RAILS_ENV=test bin/rake db:migrate --trace
  - RAILS_ENV=test bin/rake emoji
  - RAILS_ENV=test bin/rake spec --trace
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7e569f9f53d7c2c902a9 
  on_success: always  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: false     # default: false
