language: ruby
rvm:
    - 1.9.3
before_script:
    - mysql -e 'create database lodge_test'
    - cp config/database.test.yml config/database.yml
    - bundle install
script:
    - RAILS_ENV=test bundle exec rake db:migrate --trace
    - RAILS_ENV=test bundle exec rake spec --trace
