language: ruby
rvm:
    - 2.4.0
    - 2.4.1
    # - ruby-head
env:
    - DB=mysql
before_script:
    - cp config/database.test.yml config/database.yml
    - cp .env.example .env
    - bundle install
script:
    - RAILS_ENV=test bin/rake db:create --trace
    - RAILS_ENV=test bin/rake db:migrate --trace
    - RAILS_ENV=test bin/rake emoji
    - RAILS_ENV=test bin/rake spec --trace
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7e569f9f53d7c2c902a9 
  on_success: always  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: false     # default: false
